export const MESSAGING_TYPE = {
  RESPONSE: 'RESPONSE',
  UPDATE: 'UPDATE',
  MESSAGE_TAG: 'MESSAGE_TAG',
  NON_PROMOTIONAL_SUBSCRIPTION: 'NON_PROMOTIONAL_SUBSCRIPTION'
};

export const SENDER_ACTIONS = {
  MARK_SEEN: 'mark_seen',
  TYPING_ON: 'typing_on',
  TYPING_OFF: 'typing_off'
};

export const NOTIFICATION_TYPE = {
  REGULAR: 'REGULAR',
  SILENT_PUSH: 'SILENT_PUSH',
  NO_PUSH: 'NO_PUSH'
};

// offline tags
export const TAGS = {
  PAIRING_UPDATE: 'PAIRING_UPDATE',
  APPLICATION_UPDATE: 'APPLICATION_UPDATE',
  ACCOUNT_UPDATE: 'ACCOUNT_UPDATE',
  PAYMENT_UPDATE: 'PAYMENT_UPDATE',
  PERSONAL_FINANCE_UPDATE: 'PERSONAL_FINANCE_UPDATE',
  SHIPPING_UPDATE: 'SHIPPING_UPDATE',
  RESERVATION_UPDATE: 'RESERVATION_UPDATE',
  ISSUE_RESOLUTION: 'ISSUE_RESOLUTION',
  APPOINTMENT_UPDATE: 'APPOINTMENT_UPDATE',
  GAME_EVENT: 'GAME_EVENT',
  TRANSPORTATION_UPDATE: 'TRANSPORTATION_UPDATE',
  FEATURE_FUNCTIONALITY_UPDATE: 'FEATURE_FUNCTIONALITY_UPDATE',
  TICKET_UPDATE: 'TICKET_UPDATE'
};

export const ATTACHMENT_TYPE = {
  IMAGE: 'image',
  AUDIO: 'audio',
  VIDEO: 'video',
  FILE: 'file',
  TEMPLATE: 'template'
};

export const ATTACHMENT_SOURCE = {
  URL: 'url',
  FILE: 'file',
  SAVED_ASSET: 'attachment_id'
};

export const QUICKREPLY_TYPE = {
  TEXT: 'text',
  LOCATION: 'location'
};

export const MAX_QUICK_REPLIES = 11;

export const TEMPLATE_TYPE = {
  BUTTON: 'button',
  GENERIC: 'generic',
  LIST: 'list',
  OPEN_GRAPH: 'open_graph',
  MEDIA: 'media',
  RECEIPT: 'receipt',
  AIRLINE: 'airline'
};

export const BUTTON_TYPE = {
  URL: 'web_url',
  POSTBACK: 'postback',
  SHARE: 'element_share',
  BUY: 'payment',
  CALL: 'phone_number',
  LOG_IN: 'account_link',
  LOG_OUT: 'account_unlink',
  GAME_PLAY: 'game_play'
};

export const BUTTON_TEMPLATE_SUPPORT = {
  [BUTTON_TYPE.URL]: [
    TEMPLATE_TYPE.GENERIC,
    TEMPLATE_TYPE.LIST,
    TEMPLATE_TYPE.BUTTON,
    TEMPLATE_TYPE.MEDIA,
    TEMPLATE_TYPE.OPEN_GRAPH
  ],
  [BUTTON_TYPE.POSTBACK]: [
    TEMPLATE_TYPE.GENERIC,
    TEMPLATE_TYPE.LIST,
    TEMPLATE_TYPE.BUTTON,
    TEMPLATE_TYPE.MEDIA
  ],
  [BUTTON_TYPE.SHARE]: [
    TEMPLATE_TYPE.GENERIC,
    TEMPLATE_TYPE.LIST,
    TEMPLATE_TYPE.MEDIA
  ],
  [BUTTON_TYPE.BUY]: [
    TEMPLATE_TYPE.GENERIC,
    TEMPLATE_TYPE.LIST,
    TEMPLATE_TYPE.MEDIA
  ],
  [BUTTON_TYPE.CALL]: [
    TEMPLATE_TYPE.GENERIC,
    TEMPLATE_TYPE.LIST,
    TEMPLATE_TYPE.BUTTON,
    TEMPLATE_TYPE.MEDIA
  ],
  [BUTTON_TYPE.LOG_IN]: [
    TEMPLATE_TYPE.GENERIC,
    TEMPLATE_TYPE.LIST,
    TEMPLATE_TYPE.BUTTON,
    TEMPLATE_TYPE.MEDIA
  ],
  [BUTTON_TYPE.LOG_OUT]: [
    TEMPLATE_TYPE.GENERIC,
    TEMPLATE_TYPE.LIST,
    TEMPLATE_TYPE.BUTTON,
    TEMPLATE_TYPE.MEDIA
  ],
  [BUTTON_TYPE.GAME_PLAY]: [
    // todo: pending documentation update
    TEMPLATE_TYPE.GENERIC,
    TEMPLATE_TYPE.LIST,
    TEMPLATE_TYPE.BUTTON,
    TEMPLATE_TYPE.MEDIA
  ]
};

export const BUTTON_TEMPLATE_TEXT_MAXLENGTH = 640;

export const WEBVIEW_HEIGHT_RATIO = {
  COMPACT: 'compact',
  TALL: 'tall',
  FULL: 'full'
};

export default {
  MESSAGING_TYPE,
  SENDER_ACTIONS,
  NOTIFICATION_TYPE,
  ATTACHMENT_TYPE,
  ATTACHMENT_SOURCE,
  MAX_QUICK_REPLIES,
  QUICKREPLY_TYPE,
  TEMPLATE_TYPE,
  WEBVIEW_HEIGHT_RATIO,
  TAGS
};
