export const MESSAGING_TYPE = {
  RESPONSE: 'RESPONSE',
  UPDATE: 'UPDATE',
  MESSAGE_TAG: 'MESSAGE_TAG',
  NON_PROMOTIONAL_SUBSCRIPTION: 'NON_PROMOTIONAL_SUBSCRIPTION'
};

export const SENDER_ACTIONS = {
  MARK_SEEN: 'mark_seen',
  TYPING_ON: 'typing_on',
  TYPING_OFF: 'typing_off'
};

export const NOTIFICATION_TYPE = {
  REGULAR: 'REGULAR',
  SILENT_PUSH: 'SILENT_PUSH',
  NO_PUSH: 'NO_PUSH'
};

// offline tags
export const TAGS = {
  PAIRING_UPDATE: 'PAIRING_UPDATE',
  APPLICATION_UPDATE: 'APPLICATION_UPDATE',
  ACCOUNT_UPDATE: 'ACCOUNT_UPDATE',
  PAYMENT_UPDATE: 'PAYMENT_UPDATE',
  PERSONAL_FINANCE_UPDATE: 'PERSONAL_FINANCE_UPDATE',
  SHIPPING_UPDATE: 'SHIPPING_UPDATE',
  RESERVATION_UPDATE: 'RESERVATION_UPDATE',
  ISSUE_RESOLUTION: 'ISSUE_RESOLUTION',
  APPOINTMENT_UPDATE: 'APPOINTMENT_UPDATE',
  GAME_EVENT: 'GAME_EVENT',
  TRANSPORTATION_UPDATE: 'TRANSPORTATION_UPDATE',
  FEATURE_FUNCTIONALITY_UPDATE: 'FEATURE_FUNCTIONALITY_UPDATE',
  TICKET_UPDATE: 'TICKET_UPDATE'
};

export const ATTACHMENT_TYPE = {
  IMAGE: 'image',
  AUDIO: 'audio',
  VIDEO: 'video',
  FILE: 'file',
  TEMPLATE: 'template'
};

export const ATTACHMENT_SOURCE = {
  URL: 'url',
  FILE: 'file',
  SAVED_ASSET: 'attachment_id',
};

export const QUICKREPLY_TYPE = {
  TEXT: 'text',
  LOCATION: 'location'
};

export const MAX_QUICK_REPLIES = 11;

export default {
  MESSAGING_TYPE,
  SENDER_ACTIONS,
  NOTIFICATION_TYPE,
  ATTACHMENT_TYPE,
  ATTACHMENT_SOURCE,
  MAX_QUICK_REPLIES,
  QUICKREPLY_TYPE,
  TAGS
};
